[env:firebeetle2]
platform = espressif32
board = dfrobot_firebeetle2_esp32e
framework = arduino
monitor_speed = 115200
upload_speed = 921600
monitor_filters = esp32_exception_decoder
lib_deps =
    paulstoffregen/OneWire@2.3.8
build_flags =
    -DCORE_DEBUG_LEVEL=0

[env:blink]
platform = espressif32
board = dfrobot_firebeetle2_esp32e
framework = arduino
build_src_filter = -<*> +<../examples/blink/main.cpp>
monitor_speed = 115200
upload_port = COM8
upload_speed = 921600
