[env:firebeetle2]
platform = espressif32
board = dfrobot_firebeetle2_esp32e
framework = arduino
monitor_speed = 115200
upload_speed = 921600
monitor_filters = esp32_exception_decoder
build_flags =
    -DCORE_DEBUG_LEVEL=0
